version: '3'

tasks:
  # Cluster info
  info:
    desc: Show cluster information
    cmds:
      - kubectl cluster-info

  nodes:
    desc: List all nodes
    cmds:
      - kubectl get nodes -o wide

  # Namespaces
  namespaces:
    desc: List all namespaces
    cmds:
      - kubectl get ns

  # Pods
  pods:
    desc: Get all pods in all namespaces
    cmds:
      - kubectl get pods -A -o wide

  pods-ns:
    desc: Get pods in a specific namespace
    cmds:
      - kubectl get pods -n {{.NAMESPACE | default "default"}} -o wide

  describe-pod:
    desc: Describe a specific pod
    cmds:
      - kubectl describe pod {{.POD}} -n {{.NAMESPACE | default "default"}}

  logs:
    desc: Get logs of a pod
    cmds:
      - kubectl logs {{.POD}} -n {{.NAMESPACE | default "default"}} {{.CONTAINER | default ""}}

  exec:
    desc: Exec into a pod
    cmds:
      - kubectl exec -it {{.POD}} -n {{.NAMESPACE | default "default"}} -- /bin/sh

  # Deployments
  deployments:
    desc: List deployments
    cmds:
      - kubectl get deployments -A -o wide

  rollout-status:
    desc: Check rollout status of a deployment
    cmds:
      - kubectl rollout status deployment/{{.DEPLOYMENT}} -n {{.NAMESPACE | default "default"}}

  restart-deploy:
    desc: Restart a deployment
    cmds:
      - kubectl rollout restart deployment/{{.DEPLOYMENT}} -n {{.NAMESPACE | default "default"}}

  # Services
  services:
    desc: Get all services
    cmds:
      - kubectl get svc -A

  describe-svc:
    desc: Describe a specific service
    cmds:
      - kubectl describe svc {{.SERVICE}} -n {{.NAMESPACE | default "default"}}

  # ConfigMaps & Secrets
  configmaps:
    desc: List ConfigMaps
    cmds:
      - kubectl get configmaps -A

  secrets:
    desc: List Secrets
    cmds:
      - kubectl get secrets -A

  # Apply / Delete
  apply:
    desc: Apply a YAML manifest
    cmds:
      - kubectl apply -f {{.FILE}}

  delete:
    desc: Delete a resource defined in a YAML
    cmds:
      - kubectl delete -f {{.FILE}}

  # Port Forwarding
  port-forward:
    desc: Port forward a pod or service
    cmds:
      - kubectl port-forward {{.RESOURCE}} {{.LOCAL_PORT}}:{{.REMOTE_PORT}} -n {{.NAMESPACE | default "default"}}

  delete-resources:
    desc: Delete all k8s in a cluster
    cmds:
      |
      kubectl api-resources --verbs=list --namespaced -o name \
        | xargs -r -n1 kubectl delete --all --all-namespaces

      # Delete all cluster‑scoped kinds:
      kubectl api-resources --verbs=list --namespaced=false -o name \
        | xargs -r -n1 kubectl delete --all
